# Generated by Django 3.2.8 on 2021-11-25 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_email_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_method',
            field=models.CharField(choices=[('email', 'E-mail'), ('github', 'Github'), ('kakao', 'Kakao')], default='email', max_length=12),
        ),
    ]
