# Generated by Django 3.2.8 on 2021-11-23 07:04

from django.db import migrations, models
import rooms.models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_auto_20211122_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=models.ImageField(upload_to=rooms.models.Photo.user_directory_path),
        ),
    ]
